# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4774f2094c48367830832995850191683ebbe898701abc1a271209cbe8a1d6c4073b2a4bd0917c040bc79a6f17921036f2ffe32fed76c75db4b7a7262cdf6781

test:
  secret_key_base: 7e61e39d9d83086d2e1da45b9ccb6342540a8355cf1cb1b7e1a51434fb80991f3daf6d4ed6856f6633f6ab96c2a0ffbc58789ca94709862168971a3d69cf7b96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
